name: Hayokoi
description: Hayokoi!!
author: CIVN
website: http://civn.xyz/
main: xyz.civn.hayokoi.Hayokoi
version: 1.1

commands:
   hayokoi:
      description: Hayokoi!
      usage: /<command>
      permission: civn.hayokoi
      permission-message: You don't have <permission>!